export const APP_TITLE = 'Dashboard Finance RUN';
export const APP_SUBTITLE = 'Multi-company & multi-brand finance OS';

export const ENTITY_LABELS = {
  budget: 'Budget Request',
  income: 'Cash In Real',
  forecast: 'Forecast Cash In',
  forecastOut: 'Forecast Cash Out',
  outcome: 'Cash Out',
  omzet: 'Omzet',
  bank: 'Saldo Rekening',
  service: 'Biaya Layanan',
  payables: 'Hutang',
  receivables: 'Piutang',
  users: 'Users',
  brands: 'Brands',
  sources: 'Source Workbooks',
  vendors: 'Data Vendor',
  customers: 'Data Pelanggan',
};

export const TABLE_COLUMNS = {
  budget: ['Brand', 'Tgl Pengajuan', 'Tgl Dibutuhkan', 'Kategori', 'Keterangan', 'Vendor', 'ID Vendor', 'Nominal Pengajuan (Rp)', 'Nominal Dibayar (Rp)', 'Sisa Hutang (Rp)', 'Jenis Bayar', 'Tgl Pembayaran Selanjutnya', 'Tgl Pelunasan', 'Prioritas', 'Status', 'Kontrol Pengajuan', 'Form Feedback Finance'],
  income: ['Brand', 'Tanggal', 'Keterangan', 'Customer', 'Nominal', 'Bank Masuk'],
  forecast: ['Brand', 'Estimasi Cair', 'Marketplace', 'Nominal Estimasi', 'Status', 'Catatan'],
  forecastOut: ['Brand', 'Estimasi Keluar', 'Kategori', 'Nominal Estimasi', 'Status', 'Catatan'],
  outcome: ['Brand', 'Tanggal', 'Keterangan', 'Kategori', 'Jumlah (Rp)', 'Biaya (Rp)', 'Total Pengeluaran (Rp)', 'Bank Keluar'],
  omzet: ['Brand', 'Tahun', 'Bulan', 'Target Omzet', 'Realisasi Omzet', 'Selisih', 'Capaian'],
  bank: ['Brand', 'Bank', 'Saldo Awal', 'Pemasukan', 'Pengeluaran', 'Total'],
  service: ['Brand', 'Tanggal', 'Keterangan', 'Vendor', 'Nominal', 'Status'],
  payables: ['Brand', 'Nama Pemasok', 'ID Pemasok', 'Total Hutang', 'Total Dibayar', 'Sisa Hutang', 'Progress %', 'Status'],
  receivables: ['Brand', 'Nama Pelanggan', 'ID Pelanggan', 'Total Piutang', 'Total Diterima', 'Sisa Piutang', 'Progress %', 'Status'],
  users: ['Email', 'Name', 'Role', 'Company Scope', 'Brand Scope', 'Active'],
  brands: ['Company', 'Brand', 'Brand Key', 'Active', 'PIC Email'],
  sources: ['Company', 'Brand', 'Brand Key', 'Spreadsheet ID', 'Active', 'Last Imported At'],
  vendors: ['ID Vendor', 'Nama Vendor', 'PIC', 'Telepon', 'Alamat', 'Keterangan'],
  customers: ['ID Pelanggan', 'Nama Pelanggan', 'PIC', 'Telepon', 'Alamat', 'Keterangan'],
};

export const FORMS = {
  budget: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Tgl Pengajuan', label: 'Tgl Pengajuan', type: 'date' },
    { key: 'Tgl Dibutuhkan', label: 'Tgl Dibutuhkan', type: 'date' },
    { key: 'Kategori', label: 'Kategori', type: 'select', optionsKey: 'categories' },
    { key: 'Keterangan', label: 'Keterangan', type: 'textarea' },
    { key: 'Vendor', label: 'Vendor (Nama)', type: 'text' },
    { key: 'ID Vendor', label: 'ID Vendor', type: 'vendor', required: true },
    { key: 'Nominal Pengajuan', label: 'Nominal Pengajuan (Rp)', type: 'number' },
    { key: 'Nominal Dibayar', label: 'Nominal Dibayar (Rp)', type: 'number' },
    { key: 'Jenis Bayar', label: 'Jenis Bayar', type: 'select', optionsKey: 'paymentTypes' },
    { key: 'Tgl Pembayaran Selanjutnya', label: 'Tgl Pembayaran Selanjutnya', type: 'date' },
    { key: 'Tgl Pelunasan', label: 'Tgl Pelunasan', type: 'date' },
    { key: 'Prioritas', label: 'Prioritas', type: 'select', optionsKey: 'priorities' },
    { key: 'Status', label: 'Status', type: 'select', optionsKey: 'budgetStatuses' },
    { key: 'Kontrol Pengajuan', label: 'Kontrol Pengajuan', type: 'select', optionsKey: 'controls' },
    { key: 'Dokumen URL', label: 'Dokumen / Invoice URL', type: 'url' },
    { key: 'Feedback Finance', label: 'Form Feedback Finance', type: 'textarea' },
  ],
  income: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Tanggal', label: 'Tanggal', type: 'date' },
    { key: 'Keterangan', label: 'Keterangan', type: 'text' },
    { key: 'Customer', label: 'Customer', type: 'customer' },
    { key: 'Nominal', label: 'Nominal', type: 'number' },
    { key: 'Bank Masuk', label: 'Bank Masuk', type: 'select', optionsKey: 'banks' },
    { key: 'Catatan', label: 'Catatan', type: 'textarea' },
  ],
  forecast: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Estimasi Cair', label: 'Estimasi Cair', type: 'date' },
    { key: 'Marketplace', label: 'Marketplace', type: 'text' },
    { key: 'Nominal Estimasi', label: 'Nominal Estimasi', type: 'number' },
    { key: 'Status', label: 'Status', type: 'text' },
    { key: 'Catatan', label: 'Catatan', type: 'textarea' },
  ],
  forecastOut: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Estimasi Keluar', label: 'Estimasi Keluar', type: 'date' },
    { key: 'Kategori', label: 'Kategori', type: 'select', optionsKey: 'categories' },
    { key: 'Nominal Estimasi', label: 'Nominal Estimasi', type: 'number' },
    { key: 'Status', label: 'Status', type: 'text' },
    { key: 'Catatan', label: 'Catatan', type: 'textarea' },
  ],
  outcome: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Tanggal', label: 'Tanggal', type: 'date' },
    { key: 'Keterangan', label: 'Keterangan', type: 'text' },
    { key: 'Kategori', label: 'Kategori', type: 'select', optionsKey: 'categories' },
    { key: 'Jumlah', label: 'Jumlah (Rp)', type: 'number' },
    { key: 'Biaya', label: 'Biaya (Rp)', type: 'number' },
    { key: 'Bank Keluar', label: 'Bank Keluar', type: 'select', optionsKey: 'banks' },
    { key: 'Catatan', label: 'Catatan', type: 'textarea' },
  ],
  omzet: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Tahun', label: 'Tahun', type: 'number' },
    { key: 'Bulan', label: 'Bulan', type: 'select', optionsKey: 'months' },
    { key: 'Target Omzet', label: 'Target Omzet', type: 'number' },
    { key: 'Realisasi Omzet', label: 'Realisasi Omzet', type: 'number' },
  ],
  bank: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Bank', label: 'Nama Bank', type: 'select', optionsKey: 'banks' },
    { key: 'Saldo Awal', label: 'Saldo Awal', type: 'number' },
    { key: 'Pemasukan', label: 'Pemasukan', type: 'number' },
    { key: 'Pengeluaran', label: 'Pengeluaran', type: 'number' },
  ],
  service: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Tanggal', label: 'Tanggal', type: 'date' },
    { key: 'Keterangan', label: 'Keterangan', type: 'text' },
    { key: 'Vendor', label: 'Vendor', type: 'vendor' },
    { key: 'Nominal', label: 'Nominal', type: 'number' },
    { key: 'Status', label: 'Status', type: 'text' },
    { key: 'Catatan', label: 'Catatan', type: 'textarea' },
  ],
  payables: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Nama Pemasok', label: 'Nama Pemasok', type: 'text' },
    { key: 'ID Pemasok', label: 'ID Pemasok', type: 'vendor', required: true },
    { key: 'Total Hutang', label: 'Total Hutang', type: 'number' },
    { key: 'Total Dibayar', label: 'Total Dibayar', type: 'number' },
    { key: 'Status', label: 'Status', type: 'text' },
    { key: 'Source', label: 'Source', type: 'text' },
  ],
  receivables: [
    { key: 'Brand', label: 'Brand Key', type: 'brand' },
    { key: 'Nama Pelanggan', label: 'Nama Pelanggan', type: 'text' },
    { key: 'ID Pelanggan', label: 'ID Pelanggan', type: 'customer', required: true },
    { key: 'Total Piutang', label: 'Total Piutang', type: 'number' },
    { key: 'Total Diterima', label: 'Total Diterima', type: 'number' },
    { key: 'Status', label: 'Status', type: 'text' },
    { key: 'Source', label: 'Source', type: 'text' },
  ],
  users: [
    { key: 'Email', label: 'Email', type: 'email' },
    { key: 'Name', label: 'Name', type: 'text' },
    { key: 'Role', label: 'Role', type: 'select', optionsKey: 'roles' },
    { key: 'Company Scope', label: 'Company Scope', type: 'text' },
    { key: 'Brand Scope', label: 'Brand Scope', type: 'text' },
    { key: 'Active', label: 'Active', type: 'boolean' },
  ],
  brands: [
    { key: 'Company', label: 'Company', type: 'text' },
    { key: 'Brand', label: 'Brand', type: 'text' },
    { key: 'Brand Key', label: 'Brand Key', type: 'text' },
    { key: 'Active', label: 'Active', type: 'boolean' },
    { key: 'PIC Email', label: 'PIC Email', type: 'email' },
  ],
  sources: [
    { key: 'Company', label: 'Company', type: 'text' },
    { key: 'Brand', label: 'Brand', type: 'text' },
    { key: 'Brand Key', label: 'Brand Key', type: 'text' },
    { key: 'Spreadsheet ID', label: 'Spreadsheet ID', type: 'text' },
    { key: 'Active', label: 'Active', type: 'boolean' },
    { key: 'Notes', label: 'Notes', type: 'textarea' },
  ],
  vendors: [
    { key: 'ID Vendor', label: 'ID Vendor (kode unik)', type: 'text', required: true },
    { key: 'Nama Vendor', label: 'Nama Vendor / Perusahaan', type: 'text', required: true },
    { key: 'PIC', label: 'PIC (Person in Charge)', type: 'text' },
    { key: 'Telepon', label: 'No. Telepon', type: 'text' },
    { key: 'Alamat', label: 'Alamat', type: 'textarea' },
    { key: 'Keterangan', label: 'Keterangan', type: 'textarea' },
  ],
  customers: [
    { key: 'ID Pelanggan', label: 'ID Pelanggan (kode unik)', type: 'text', required: true },
    { key: 'Nama Pelanggan', label: 'Nama Pelanggan / Perusahaan', type: 'text', required: true },
    { key: 'PIC', label: 'PIC (Person in Charge)', type: 'text' },
    { key: 'Telepon', label: 'No. Telepon', type: 'text' },
    { key: 'Alamat', label: 'Alamat', type: 'textarea' },
    { key: 'Keterangan', label: 'Keterangan', type: 'textarea' },
  ],
};

export const CHART_COLORS = ['#0f766e', '#2563eb', '#f9735b', '#f59e0b', '#7c3aed', '#16a34a', '#e11d48', '#0891b2', '#84cc16', '#d946ef'];

export const VIEWS = ['command', 'analytics', 'operations', 'approval', 'master', 'documentation'];
export const VIEW_TITLES = {
  command: 'Command Center',
  analytics: 'Analytics Board',
  operations: 'Operasional Harian',
  approval: 'Approval Finance',
  master: 'Master Data',
  documentation: 'Dokumentasi & Panduan',
};
