-- Adds Forecast Cash Out, mirroring fin_forecast_cashin, needed for EWS indicators
-- #7 Forecast Cash Position and #8 Projected Cash Position
-- (RAW DATA DASHBOARD FINANCE/Early Warning System.docx)
--
-- Run manually in the Supabase SQL editor (Claude has no DDL access to production).
-- Before running: open Table Editor > fin_forecast_cashin and check its `id` column
-- type (uuid vs bigint identity) — match it below if it differs.
--
-- Note: this intentionally does NOT enable Row Level Security here — RLS for this
-- table (and every other fin_* table) is turned on together in
-- 0002_auth_and_rls.sql, once real Supabase Auth accounts exist to enforce it against.

create table if not exists fin_forecast_cashout (
  id bigint generated by default as identity primary key,
  brand_key text not null,
  estimasi_keluar date not null,
  kategori text,
  nominal_estimasi numeric not null default 0,
  status text,
  catatan text,
  created_at timestamptz not null default now()
);
