-- Forecasting & Controlling Budget — replicates "CV LBP - Forecasting & Controlling
-- Budget - 2026.xlsx": a full P&L (OMZET → COGS → LABA KOTOR → BEBAN OPERASIONAL by
-- category → LABA BERSIH) tracked as Nilai Anggaran (budget) vs Nilai Realisasi
-- (actual) per brand, per month. line_key identifies which P&L row this is —
-- the fixed catalog lives in src/utils/forecastLineItems.js, not in the DB, since
-- the row list/labels/subtotal formulas never vary per brand or period.
--
-- Run manually in the Supabase SQL editor (Claude has no DDL access to production).

create table if not exists fin_forecast_budget (
  id bigint generated by default as identity primary key,
  brand_key text not null,
  tahun int not null,
  bulan int not null check (bulan between 1 and 12),
  line_key text not null,
  nilai_anggaran numeric not null default 0,
  nilai_realisasi numeric not null default 0,
  keterangan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_key, tahun, bulan, line_key)
);

alter table fin_forecast_budget enable row level security;

-- Read: same rule as every other brand-scoped table (0002_auth_and_rls.sql) —
-- superadmin/finance/owner see every brand, pic_brand only their own.
create policy "fin_forecast_budget_select" on fin_forecast_budget for select
  using (
    auth_active() and (
      auth_role() in ('superadmin', 'finance', 'owner')
      or (auth_role() = 'pic_brand' and brand_key = auth_brand_scope())
    )
  );

-- Write: finance-only, same group as fin_omzet/fin_bank/fin_service (owner is
-- read-only per 0011, pic_brand isn't granted this planning tool).
create policy "fin_forecast_budget_write" on fin_forecast_budget for all
  using (auth_active() and auth_role() in ('superadmin', 'finance'))
  with check (auth_active() and auth_role() in ('superadmin', 'finance'));
